
services:
  frontend:
    restart: always
    build:
      context: ./poker_frontend
      dockerfile: Dockerfile
    image: poker_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./poker_backend
      dockerfile: Dockerfile
    image: poker_backend
    ports:
      - "8000:8080"
    depends_on:
      - db
    env_file:
      - ./poker_backend/.env

  db:
    image: postgres:16
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - ./poker_backend/.env
