
services:
  frontend:
    restart: always
    build:
      context: ./poker_frontend
      dockerfile: Dockerfile
    image: poker_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./poker_backend
      dockerfile: Dockerfile
    image: poker_backend
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db  # Use db container as the host
      - POSTGRES_PORT=5432

  db:
    image: postgres:16
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
